# render.yaml

services:
  - type: web
    name: wakili-ai-telegram-bot
    region: oregon
    env: python
    plan: free
    branch: master # Or 'main'
    buildCommand: "pip install -r requirements.txt"
    # THE FIX IS HERE: Use Hypercorn to run the app
    startCommand: "hypercorn telegram_bot:app --bind 0.0.0.0:$PORT"
    healthCheckPath: /health
    envVars:
      - fromGroup: wakili-ai-secrets
      - key: PYTHON_VERSION
        value: 3.11.4