# render.yaml

services:
  - type: web # Changed from 'worker' to 'web'
    name: wakili-ai-telegram-bot
    region: oregon
    env: python
    plan: free
    branch: master # Or 'main' depending on your branch name
    buildCommand: "pip install -r requirements.txt"
    # The start command is now for the Flask web server
    startCommand: "python telegram_bot.py"
    healthCheckPath: /health # A simple URL to check if the app is alive
    envVars:
      - fromGroup: wakili-ai-secrets
      - key: PYTHON_VERSION
        value: 3.11.4